# Generated by Django 6.1.1 on 2026-09-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(upload_to='agents/'),
        ),
    ]
