# Generated by Django 6.1.1 on 2026-09-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='whatsapp',
            field=models.CharField(max_length=30),
        ),
    ]
