# Generated by Django 6.1.1 on 2026-09-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_owner_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='order',
        ),
    ]
