# Generated by Django 6.1.1 on 2026-09-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_propertyimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['created_at']},
        ),
    ]
