# Generated by Django 6.1.1 on 2026-09-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
    ]
